#include "demo_fonts.h"

#include <cstddef>

// Generated by drizzy_bin2c from assets/fonts (see CMakeLists.txt).
extern const unsigned char kDemoFont_Monocraft[];
extern const size_t kDemoFont_MonocraftSize;
extern const unsigned char kDemoFont_PressStart2P_Regular[];
extern const size_t kDemoFont_PressStart2P_RegularSize;
extern const unsigned char kDemoFont_JetBrainsMono_Regular[];
extern const size_t kDemoFont_JetBrainsMono_RegularSize;
extern const unsigned char kDemoFont_Orbitron_Variable[];
extern const size_t kDemoFont_Orbitron_VariableSize;
extern const unsigned char kDemoFont_Rajdhani_Medium[];
extern const size_t kDemoFont_Rajdhani_MediumSize;
extern const unsigned char kDemoFont_VarelaRound_Regular[];
extern const size_t kDemoFont_VarelaRound_RegularSize;

using namespace drizzy;

namespace demo {

std::vector<DemoFont> AddDemoFonts(FontAtlas& atlas, Font* defaultFont) {
    struct Entry {
        const char* name;
        const unsigned char* data;
        size_t size;
        float fontSize;
    };
    const Entry entries[] = {
        {"Monocraft (Minecraft style)", kDemoFont_Monocraft, kDemoFont_MonocraftSize, 16.0f},
        {"Press Start 2P (8-bit)", kDemoFont_PressStart2P_Regular, kDemoFont_PressStart2P_RegularSize, 11.0f},
        {"JetBrains Mono", kDemoFont_JetBrainsMono_Regular, kDemoFont_JetBrainsMono_RegularSize, 15.0f},
        {"Orbitron (sci-fi)", kDemoFont_Orbitron_Variable, kDemoFont_Orbitron_VariableSize, 14.0f},
        {"Rajdhani (HUD)", kDemoFont_Rajdhani_Medium, kDemoFont_Rajdhani_MediumSize, 18.0f},
        {"Varela Round", kDemoFont_VarelaRound_Regular, kDemoFont_VarelaRound_RegularSize, 16.0f},
    };
    std::vector<DemoFont> fonts;
    if (defaultFont) fonts.push_back({"Inter", defaultFont, 16.0f});
    for (const Entry& e : entries) {
        if (Font* font = atlas.AddFont(e.data, e.size)) fonts.push_back({e.name, font, e.fontSize});
    }
    return fonts;
}

} // namespace demo
