// Build-time helper: turns a binary file into a C++ source file that defines it as a byte array.
//   drizzy_bin2c <input> <output.cpp> <symbol>
// defines `extern const unsigned char <symbol>[]` and `extern const size_t <symbol>Size`.
#include <cstdio>
#include <vector>

int main(int argc, char** argv) {
    if (argc != 4) {
        std::fprintf(stderr, "usage: drizzy_bin2c <input> <output.cpp> <symbol>\n");
        return 2;
    }
    FILE* in = nullptr;
    FILE* out = nullptr;
    if (fopen_s(&in, argv[1], "rb") != 0 || !in) {
        std::fprintf(stderr, "drizzy_bin2c: cannot read %s\n", argv[1]);
        return 1;
    }
    std::vector<unsigned char> data;
    unsigned char buffer[65536];
    for (size_t n; (n = std::fread(buffer, 1, sizeof(buffer), in)) > 0;) data.insert(data.end(), buffer, buffer + n);
    std::fclose(in);

    if (fopen_s(&out, argv[2], "wb") != 0 || !out) {
        std::fprintf(stderr, "drizzy_bin2c: cannot write %s\n", argv[2]);
        return 1;
    }
    std::fprintf(out, "// Generated by drizzy_bin2c from %s. Do not edit.\n#include <cstddef>\n\n", argv[1]);
    std::fprintf(out, "extern const unsigned char %s[];\nextern const size_t %sSize;\n\n", argv[3], argv[3]);
    std::fprintf(out, "alignas(16) const unsigned char %s[] = {\n", argv[3]);
    for (size_t i = 0; i < data.size(); ++i) {
        std::fprintf(out, "%u,%s", unsigned(data[i]), (i % 32 == 31) ? "\n" : "");
    }
    std::fprintf(out, "\n};\nconst size_t %sSize = %zu;\n", argv[3], data.size());
    const bool ok = std::ferror(out) == 0;
    std::fclose(out);
    return ok ? 0 : 1;
}
